### ISSUE TITLE
Subtask: Create the Adapter file

### ISSUE THREAD

**Issue by KyletheWolff** [TheLearningCurve/RevampNutritionAPI#2]
#1

Add to new libraries 
- gson-2.3.1.jar - Will allow us to parse out the JSON response
- retrofit-1.9.0.jar - Will allow us to actually connect to the service

Name the file `Adapter.java`

In the Adapter File we will need the methods which will be as such
`public void searchForFood() {}`
`public void getItem() {}`
`public void typeAhead() {}`

**Comment by BrandonVanderMey** [comment]
What package should this go in?

**Comment by KyletheWolff** [comment]
Created waiting for Merge

**Comment by KyletheWolff** [comment]
Closed
