### ISSUE TITLE
Design for the nutrition items / buttons on the left panel

### ISSUE THREAD

**Issue by KyletheWolff** [TheLearningCurve/RevampNutritionAPI#35]
Here is what we get back from the service: 

Response: 

``` javascript
{
  "exact": false,
  "total": 19059,
  "status": 200,
  "results": [
    {
      "item_name": "Pizzaghetti* - Pepperoni Pizza",
      "brand_name": "Boston Pizza",
      "thumbnail": "https://d1r9wva3zcpswd.cloudfront.net/533d7cc35b8015402e5ce10d.jpg",
      "nutrient_name": "Calories",
      "nutrient_value": 760,
      "nutrient_uom": "kcal",
      "serving_qty": 411,
      "serving_uom": "g",
      "resource_id": "JayDhyDo6",
      "nutrients": null
    }
```

We are only using item name and brand name right now and the thumbnail. 

The order which it goes is [ Picture - Item Name on top - Bottom says from "Brand Name" ]

**Comment by BrandonVanderMey** [comment]
Are you going to design this button with CSS?  This will eliminate the need for an image file like we have now.

**Comment by KyletheWolff** [comment]
This is for Brad to make comps. Brad once you have the designs made you can create the story as well.

**Comment by BrandonVanderMey** [comment]
He should be able to make the buttons all in CSS and when he makes the FXML component.  After that we add the CSS file that he creates to the FXMLLoader object.  This is just one of the many ways we can do this.

**Comment by KyletheWolff** [comment]
Brad will be making design comps and we actually create to the comp
