### ISSUE TITLE
Create the custom JPanels for the right and left and top

### ISSUE THREAD

**Issue by KyletheWolff** [TheLearningCurve/RevampNutritionAPI#8]
Name in `LeftPanel, RightPanel`, `TopPanel`
Again, add what we need to make this correct for out design.
Add to the `gui` package

**Comment by BrandonVanderMey** [comment]
Ah, good!  I'm glad we're on top of this lol.   I was going to ask what we should call our three main panels.

**Comment by KyletheWolff** [comment]
Done!
