### ISSUE TITLE
Create Custom JPanel for the populated Search(List) View

### ISSUE THREAD

**Issue by KyletheWolff** [TheLearningCurve/RevampNutritionAPI#9]
Create the JPanel and make it look like - 
Name it SearchView
The top word is the Item Name = JLabel itemName
The bottom word is the Brand Name = JLabel brandName
To the left we can actually use an Image Icon and create a JLabel that the Image Icon goes into. Super Easy. 
![capture](https://cloud.githubusercontent.com/assets/10425034/7521055/2203fb40-f4b9-11e4-9ffc-3eae11e1a5d8.PNG)

The hardest part is going to be populating the data but that will be its own story.

**Comment by BrandonVanderMey** [comment]
This will be housed in the LeftPanel class.

**Comment by BrandonVanderMey** [comment]
File is set up.
